/*
 * battery_mgmt.c
 *
 *  Created on: 10 Jan 2026
 *      Author: michaelsmart
 */
#include "battery_mgmt.h"
#include "stm32f4xx_hal.h"

extern ADC_HandleTypeDef hadc1; // generated by CubeMX or your init code

uint8_t Get_Battery_Volt(void)
{
	ADC->CCR |= ADC_CCR_VBATE;
    float vdda_volts = 3.29;
    (void)HAL_ADC_Start(&hadc1);
    (void)HAL_ADC_PollForConversion(&hadc1, 10);
    uint32_t raw = HAL_ADC_GetValue(&hadc1);
    (void)HAL_ADC_Stop(&hadc1);

    // 12-bit ADC full scale = 4095
    // VBAT channel reports VBAT/2 -> multiply by 2
    float vbat = (2.0f * vdda_volts * (float)raw) / 4095.0f *2;

    // Convert volts → 20 mV units (rounded)
    uint32_t mv = (uint32_t)(vbat * 1000.0f + 0.5f);
    uint32_t units = mv / 20U;

    ADC->CCR &= ~ADC_CCR_VBATE;

    //to clamp and prevent wrap around
    if (units > 255U)
    	units = 255U;

    return (uint8_t)units;

}

