/*
 * battery_mgmt.c
 *
 *  Created on: 10 Jan 2026
 *      Author: michaelsmart
 */
#include "battery_mgmt.h"
#include "stm32f4xx_hal.h"

extern ADC_HandleTypeDef hadc1; // generated by CubeMX or your init code

void ADC1_ConfigChannel_VBAT(void)
{
    ADC_ChannelConfTypeDef sConfig = {0};

    // Enable internal VBAT channel path (HAL macro exists on STM32F4 HAL)
    // If your HAL doesn't provide it, see the register-level version below.
    __HAL_ADC_ENABLE_VBAT();

    sConfig.Channel      = ADC_CHANNEL_VBAT;          // usually maps to channel 18
    sConfig.Rank         = 1;
    sConfig.SamplingTime = ADC_SAMPLETIME_480CYCLES;  // internal channels need long sample time
    (void)HAL_ADC_ConfigChannel(&hadc1, &sConfig);
}

uint8_t Get_Battery_Volt(void)
{
    ADC1_ConfigChannel_VBAT();
    float vdda_volts = 3.3f;
    (void)HAL_ADC_Start(&hadc1);
    (void)HAL_ADC_PollForConversion(&hadc1, 10);
    uint32_t raw = HAL_ADC_GetValue(&hadc1);
    (void)HAL_ADC_Stop(&hadc1);

    // 12-bit ADC full scale = 4095
    // VBAT channel reports VBAT/2 -> multiply by 2
    float vbat = (2.0f * vdda_volts * (float)raw) / 4095.0f;

    // Optional: disable VBAT channel path to reduce battery drain through internal divider
    __HAL_ADC_DISABLE_VBAT();

    return vbat;
}

